Flect.Compiler.Syntax.Token[type: :identifier, value: "foo", location: Flect.Compiler.Syntax.Location[file: "ident2.fl", line: 1, column: 1]]
Flect.Compiler.Syntax.Token[type: :colon_colon, value: "::", location: Flect.Compiler.Syntax.Location[file: "ident2.fl", line: 1, column: 4]]
Flect.Compiler.Syntax.Token[type: :identifier, value: "bar", location: Flect.Compiler.Syntax.Location[file: "ident2.fl", line: 1, column: 6]]
