Flect.Compiler.Syntax.Token[type: :let, value: "let", location: Flect.Compiler.Syntax.Location[file: "keyword.fl", line: 2, column: 1]]
Flect.Compiler.Syntax.Token[type: :mut, value: "mut", location: Flect.Compiler.Syntax.Location[file: "keyword.fl", line: 3, column: 1]]
Flect.Compiler.Syntax.Token[type: :if, value: "if", location: Flect.Compiler.Syntax.Location[file: "keyword.fl", line: 4, column: 1]]
