module_declaration (1,5) [ "pub" (1,1), "mod" (1,5), "{" (1,13), "}" (3,1) ]
{
    qualified_name (1,9) [  ]
    {
        simple_name (1,9) [ "Bar" (1,9) ]
        {
        }
    }
    attribute (2,13) [ "@" (2,9), "[" (2,11), "]" (2,46) ]
    {
        attribute_name (2,13) [ "enum" (2,13) ]
        {
        }
        attribute_arguments (2,18) [ "(" (2,18), "," (2,30), ")" (2,44) ]
        {
            attribute_argument (2,19) [  ]
            {
                attribute_name (2,19) [ "label" (2,19) ]
                {
                }
                attribute_value (2,25) [  ]
                {
                    attribute_char_literal (2,27) [ "'f'" (2,27) ]
                    {
                    }
                }
            }
            attribute_argument (2,32) [  ]
            {
                attribute_name (2,32) [ "type" (2,32) ]
                {
                }
                attribute_value (2,37) [  ]
                {
                    attribute_typed_int_literal (2,39) [ "2" (2,39) ]
                    {
                    }
                }
            }
        }
    }
}
