module_declaration (1,5) [ "pub" (1,1), "mod" (1,5), "{" (1,23), "}" (8,1) ]
{
    qualified_name (1,9) [  ]
    {
        simple_name (1,9) [ "generic_types" (1,9) ]
        {
        }
    }
    struct_declaration (2,9) [ "pub" (2,5), "struct" (2,9), "{" (2,29), "}" (7,5) ]
    {
        simple_name (2,16) [ "GenericTypes" (2,16) ]
        {
        }
        field_declaration (3,13) [ "pub" (3,9), ":" (3,15), ";" (3,25) ]
        {
            simple_name (3,13) [ "a" (3,13) ]
            {
            }
            nominal_type (3,17) [  ]
            {
                qualified_name (3,17) [  ]
                {
                    simple_name (3,17) [ "foo" (3,17) ]
                    {
                    }
                }
                type_arguments (3,20) [ "[" (3,20), "]" (3,24) ]
                {
                    nominal_type (3,21) [  ]
                    {
                        qualified_name (3,21) [  ]
                        {
                            simple_name (3,21) [ "bar" (3,21) ]
                            {
                            }
                        }
                    }
                }
            }
        }
        field_declaration (4,13) [ "pub" (4,9), ":" (4,15), ";" (4,30) ]
        {
            simple_name (4,13) [ "b" (4,13) ]
            {
            }
            nominal_type (4,17) [  ]
            {
                qualified_name (4,17) [  ]
                {
                    simple_name (4,17) [ "foo" (4,17) ]
                    {
                    }
                }
                type_arguments (4,20) [ "[" (4,20), "," (4,24), "]" (4,29) ]
                {
                    nominal_type (4,21) [  ]
                    {
                        qualified_name (4,21) [  ]
                        {
                            simple_name (4,21) [ "bar" (4,21) ]
                            {
                            }
                        }
                    }
                    nominal_type (4,26) [  ]
                    {
                        qualified_name (4,26) [  ]
                        {
                            simple_name (4,26) [ "baz" (4,26) ]
                            {
                            }
                        }
                    }
                }
            }
        }
        field_declaration (5,13) [ "pub" (5,9), ":" (5,15), ";" (5,33) ]
        {
            simple_name (5,13) [ "c" (5,13) ]
            {
            }
            nominal_type (5,17) [  ]
            {
                qualified_name (5,17) [  ]
                {
                    simple_name (5,17) [ "foo" (5,17) ]
                    {
                    }
                }
                type_arguments (5,20) [ "[" (5,20), "," (5,25), "]" (5,32) ]
                {
                    unsafe_pointer_type (5,21) [ "*" (5,21) ]
                    {
                        nominal_type (5,22) [  ]
                        {
                            qualified_name (5,22) [  ]
                            {
                                simple_name (5,22) [ "i32" (5,22) ]
                                {
                                }
                            }
                        }
                    }
                    managed_pointer_type (5,27) [ "@" (5,27) ]
                    {
                        nominal_type (5,28) [  ]
                        {
                            qualified_name (5,28) [  ]
                            {
                                simple_name (5,28) [ "self" (5,28) ]
                                {
                                }
                            }
                        }
                    }
                }
            }
        }
        field_declaration (6,13) [ "pub" (6,9), ":" (6,15), ";" (6,31) ]
        {
            simple_name (6,13) [ "d" (6,13) ]
            {
            }
            nominal_type (6,17) [  ]
            {
                qualified_name (6,17) [  ]
                {
                    simple_name (6,17) [ "foo" (6,17) ]
                    {
                    }
                }
                type_arguments (6,20) [ "[" (6,20), "]" (6,30) ]
                {
                    tuple_type (6,21) [ "(" (6,21), "," (6,23), "," (6,26), ")" (6,29) ]
                    {
                        nominal_type (6,22) [  ]
                        {
                            qualified_name (6,22) [  ]
                            {
                                simple_name (6,22) [ "a" (6,22) ]
                                {
                                }
                            }
                        }
                        nominal_type (6,25) [  ]
                        {
                            qualified_name (6,25) [  ]
                            {
                                simple_name (6,25) [ "b" (6,25) ]
                                {
                                }
                            }
                        }
                        nominal_type (6,28) [  ]
                        {
                            qualified_name (6,28) [  ]
                            {
                                simple_name (6,28) [ "c" (6,28) ]
                                {
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
