(module_declaration <"module_multi_decl.fl", 1, 1>,
 (mod_keyword: "mod" <"module_multi_decl.fl", 1, 1>,
  opening_brace: "{" <"module_multi_decl.fl", 1, 9>,
  closing_brace: "}" <"module_multi_decl.fl", 2, 1>),
 (),
 (name: (qualified_name <"module_multi_decl.fl", 1, 5>,
  (),
  ((simple_name <"module_multi_decl.fl", 1, 5>,
    (name: "foo" <"module_multi_decl.fl", 1, 5>),
    (),
    ()
   )),
  ()
 ))
)
(module_declaration <"module_multi_decl.fl", 4, 1>,
 (mod_keyword: "mod" <"module_multi_decl.fl", 4, 1>,
  opening_brace: "{" <"module_multi_decl.fl", 4, 14>,
  closing_brace: "}" <"module_multi_decl.fl", 5, 1>),
 (),
 (name: (qualified_name <"module_multi_decl.fl", 4, 5>,
  (separator: "::" <"module_multi_decl.fl", 4, 8>),
  ((simple_name <"module_multi_decl.fl", 4, 5>,
    (name: "foo" <"module_multi_decl.fl", 4, 5>),
    (),
    ()
   ),
   (simple_name <"module_multi_decl.fl", 4, 10>,
    (name: "bar" <"module_multi_decl.fl", 4, 10>),
    (),
    ()
   )),
  ()
 ))
)
(module_declaration <"module_multi_decl.fl", 7, 1>,
 (mod_keyword: "mod" <"module_multi_decl.fl", 7, 1>,
  opening_brace: "{" <"module_multi_decl.fl", 7, 19>,
  closing_brace: "}" <"module_multi_decl.fl", 8, 1>),
 (),
 (name: (qualified_name <"module_multi_decl.fl", 7, 5>,
  (separator: "::" <"module_multi_decl.fl", 7, 8>,
   separator: "::" <"module_multi_decl.fl", 7, 13>),
  ((simple_name <"module_multi_decl.fl", 7, 5>,
    (name: "foo" <"module_multi_decl.fl", 7, 5>),
    (),
    ()
   ),
   (simple_name <"module_multi_decl.fl", 7, 10>,
    (name: "bar" <"module_multi_decl.fl", 7, 10>),
    (),
    ()
   ),
   (simple_name <"module_multi_decl.fl", 7, 15>,
    (name: "baz" <"module_multi_decl.fl", 7, 15>),
    (),
    ()
   )),
  ()
 ))
)
