module_declaration (1,5) [ "pub" (1,1), "mod" (1,5), "{" (1,23), "}" (10,1) ]
{
    qualified_name (1,9) [  ]
    {
        simple_name (1,9) [ "pointer_types" (1,9) ]
        {
        }
    }
    struct_declaration (2,9) [ "pub" (2,5), "struct" (2,9), "{" (2,29), "}" (9,5) ]
    {
        simple_name (2,16) [ "PointerTypes" (2,16) ]
        {
        }
        field_declaration (3,13) [ "pub" (3,9), ":" (3,15), ";" (3,21) ]
        {
            simple_name (3,13) [ "a" (3,13) ]
            {
            }
            unsafe_pointer_type (3,17) [ "*" (3,17) ]
            {
                nominal_type (3,18) [  ]
                {
                    qualified_name (3,18) [  ]
                    {
                        simple_name (3,18) [ "foo" (3,18) ]
                        {
                        }
                    }
                }
            }
        }
        field_declaration (4,13) [ "pub" (4,9), ":" (4,15), ";" (4,23) ]
        {
            simple_name (4,13) [ "b" (4,13) ]
            {
            }
            unsafe_pointer_type (4,17) [ "*" (4,17) ]
            {
                unsafe_pointer_type (4,18) [ "*" (4,18) ]
                {
                    unsafe_pointer_type (4,19) [ "*" (4,19) ]
                    {
                        nominal_type (4,20) [  ]
                        {
                            qualified_name (4,20) [  ]
                            {
                                simple_name (4,20) [ "bar" (4,20) ]
                                {
                                }
                            }
                        }
                    }
                }
            }
        }
        field_declaration (5,13) [ "pub" (5,9), ":" (5,15), ";" (5,23) ]
        {
            simple_name (5,13) [ "c" (5,13) ]
            {
            }
            managed_pointer_type (5,17) [ "@" (5,17) ]
            {
                nominal_type (5,18) [  ]
                {
                    qualified_name (5,18) [  ]
                    {
                        simple_name (5,18) [ "a" (5,18) ]
                        {
                        }
                    }
                    type_arguments (5,19) [ "[" (5,19), "]" (5,22) ]
                    {
                        managed_pointer_type (5,20) [ "@" (5,20) ]
                        {
                            nominal_type (5,21) [  ]
                            {
                                qualified_name (5,21) [  ]
                                {
                                    simple_name (5,21) [ "b" (5,21) ]
                                    {
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        field_declaration (6,13) [ "pub" (6,9), ":" (6,15), ";" (6,34) ]
        {
            simple_name (6,13) [ "d" (6,13) ]
            {
            }
            general_pointer_type (6,17) [ "&" (6,17) ]
            {
                tuple_type (6,18) [ "(" (6,18), "," (6,22), "," (6,27), ")" (6,33) ]
                {
                    nominal_type (6,19) [  ]
                    {
                        qualified_name (6,19) [  ]
                        {
                            simple_name (6,19) [ "foo" (6,19) ]
                            {
                            }
                        }
                    }
                    nominal_type (6,24) [  ]
                    {
                        qualified_name (6,24) [  ]
                        {
                            simple_name (6,24) [ "bar" (6,24) ]
                            {
                            }
                        }
                    }
                    general_pointer_type (6,29) [ "&" (6,29) ]
                    {
                        nominal_type (6,30) [  ]
                        {
                            qualified_name (6,30) [  ]
                            {
                                simple_name (6,30) [ "baz" (6,30) ]
                                {
                                }
                            }
                        }
                    }
                }
            }
        }
        field_declaration (7,13) [ "pub" (7,9), ":" (7,15), ";" (7,25) ]
        {
            simple_name (7,13) [ "e" (7,13) ]
            {
            }
            managed_pointer_type (7,17) [ "@" (7,17), "imm" (7,18) ]
            {
                nominal_type (7,22) [  ]
                {
                    qualified_name (7,22) [  ]
                    {
                        simple_name (7,22) [ "int" (7,22) ]
                        {
                        }
                    }
                }
            }
        }
        field_declaration (8,13) [ "pub" (8,9), ":" (8,15), ";" (8,26) ]
        {
            simple_name (8,13) [ "f" (8,13) ]
            {
            }
            managed_pointer_type (8,17) [ "@" (8,17), "mut" (8,18) ]
            {
                nominal_type (8,22) [  ]
                {
                    qualified_name (8,22) [  ]
                    {
                        simple_name (8,22) [ "self" (8,22) ]
                        {
                        }
                    }
                }
            }
        }
    }
}
