module_declaration (1,5) [ "pub" (1,1), "mod" (1,5), "{" (1,20), "}" (8,1) ]
{
    qualified_name (1,9) [  ]
    {
        simple_name (1,9) [ "qual_types" (1,9) ]
        {
        }
    }
    struct_declaration (2,9) [ "pub" (2,5), "struct" (2,9), "{" (2,26), "}" (7,5) ]
    {
        simple_name (2,16) [ "QualTypes" (2,16) ]
        {
        }
        field_declaration (3,13) [ "pub" (3,9), ":" (3,15), ";" (3,20) ]
        {
            simple_name (3,13) [ "a" (3,13) ]
            {
            }
            nominal_type (3,17) [  ]
            {
                qualified_name (3,17) [  ]
                {
                    simple_name (3,17) [ "foo" (3,17) ]
                    {
                    }
                }
            }
        }
        field_declaration (4,13) [ "pub" (4,9), ":" (4,15), ";" (4,25) ]
        {
            simple_name (4,13) [ "b" (4,13) ]
            {
            }
            nominal_type (4,17) [  ]
            {
                qualified_name (4,17) [ "::" (4,20) ]
                {
                    simple_name (4,17) [ "foo" (4,17) ]
                    {
                    }
                    simple_name (4,22) [ "bar" (4,22) ]
                    {
                    }
                }
            }
        }
        field_declaration (5,13) [ "pub" (5,9), ":" (5,15), ";" (5,30) ]
        {
            simple_name (5,13) [ "c" (5,13) ]
            {
            }
            nominal_type (5,17) [  ]
            {
                qualified_name (5,17) [ "::" (5,20), "::" (5,25) ]
                {
                    simple_name (5,17) [ "foo" (5,17) ]
                    {
                    }
                    simple_name (5,22) [ "baz" (5,22) ]
                    {
                    }
                    simple_name (5,27) [ "baz" (5,27) ]
                    {
                    }
                }
            }
        }
        field_declaration (6,13) [ "pub" (6,9), ":" (6,15), ";" (6,35) ]
        {
            simple_name (6,13) [ "d" (6,13) ]
            {
            }
            nominal_type (6,17) [  ]
            {
                qualified_name (6,17) [ "::" (6,20) ]
                {
                    simple_name (6,17) [ "foo" (6,17) ]
                    {
                    }
                    simple_name (6,22) [ "bar" (6,22) ]
                    {
                    }
                }
                type_arguments (6,25) [ "[" (6,25), "]" (6,34) ]
                {
                    nominal_type (6,26) [  ]
                    {
                        qualified_name (6,26) [ "::" (6,29) ]
                        {
                            simple_name (6,26) [ "baz" (6,26) ]
                            {
                            }
                            simple_name (6,31) [ "qux" (6,31) ]
                            {
                            }
                        }
                    }
                }
            }
        }
    }
}
