module_declaration (1,5) [ "pub" (1,1), "mod" (1,5), "{" (1,21), "}" (5,1) ]
{
    qualified_name (1,9) [  ]
    {
        simple_name (1,9) [ "struct_decl" (1,9) ]
        {
        }
    }
    struct_declaration (2,9) [ "pub" (2,5), "struct" (2,9), "{" (2,20), "}" (4,5) ]
    {
        simple_name (2,16) [ "bar" (2,16) ]
        {
        }
        field_declaration (3,13) [ "pub" (3,9), ";" (3,17) ]
        {
            simple_name (3,13) [ "baz" (3,13) ]
            {
            }
        }
    }
}
