module_declaration (1,5) [ "pub" (1,1), "mod" (1,5), "{" (1,13), "}" (3,1) ]
{
    qualified_name (1,9) [  ]
    {
        simple_name (1,9) [ "foo" (1,9) ]
        {
        }
    }
    type_declaration (2,10) [ "type" (2,10), "=" (2,36), ";" (2,44) ]
    {
        simple_name (2,15) [ "magic_int" (2,15) ]
        {
        }
        nominal_type (2,38) [  ]
        {
            qualified_name (2,38) [  ]
            {
                simple_name (2,38) [ "int" (2,38) ]
                {
                }
            }
            type_arguments (2,41) [ "[" (2,41), "]" (2,43) ]
            {
                nominal_type (2,42) [  ]
                {
                    qualified_name (2,42) [  ]
                    {
                        simple_name (2,42) [ "T" (2,42) ]
                        {
                        }
                    }
                }
            }
        }
        type_parameters (2,24) [ "[" (2,24), "]" (2,34) ]
        {
            type_parameter (2,25) [  ]
            {
                simple_name (2,25) [ "T" (2,25) ]
                {
                }
                type_parameter_bounds (2,27) [ ":" (2,27), "&" (2,31) ]
                {
                    nominal_type (2,29) [  ]
                    {
                        qualified_name (2,29) [  ]
                        {
                            simple_name (2,29) [ "U" (2,29) ]
                            {
                            }
                        }
                    }
                    nominal_type (2,33) [  ]
                    {
                        qualified_name (2,33) [  ]
                        {
                            simple_name (2,33) [ "V" (2,33) ]
                            {
                            }
                        }
                    }
                }
            }
        }
    }
}
