module_declaration (1,5) [ "pub" (1,1), "mod" (1,5), "{" (1,13), "}" (4,1) ]
{
    qualified_name (1,9) [  ]
    {
        simple_name (1,9) [ "foo" (1,9) ]
        {
        }
    }
    use_declaration (2,5) [ "use" (2,5), ";" (2,18) ]
    {
        qualified_name (2,9) [ "::" (2,13) ]
        {
            simple_name (2,9) [ "core" (2,9) ]
            {
            }
            simple_name (2,15) [ "dbg" (2,15) ]
            {
            }
        }
    }
    use_declaration (3,5) [ "use" (3,5), "ext" (3,9), ";" (3,27) ]
    {
        qualified_name (3,13) [ "::" (3,17) ]
        {
            simple_name (3,13) [ "core" (3,13) ]
            {
            }
            simple_name (3,19) [ "volatile" (3,19) ]
            {
            }
        }
    }
}
