module_declaration (1,5) [ "pub" (1,1), "mod" (1,5), "{" (1,22), "}" (7,1) ]
{
    qualified_name (1,9) [  ]
    {
        simple_name (1,9) [ "vector_types" (1,9) ]
        {
        }
    }
    struct_declaration (2,9) [ "pub" (2,5), "struct" (2,9), "{" (2,28), "}" (6,5) ]
    {
        simple_name (2,16) [ "VectorTypes" (2,16) ]
        {
        }
        field_declaration (3,13) [ "pub" (3,9), ":" (3,15), ";" (3,28) ]
        {
            simple_name (3,13) [ "a" (3,13) ]
            {
            }
            vector_type (3,17) [ "[" (3,17), ".." (3,22), "32" (3,25), "]" (3,27) ]
            {
                nominal_type (3,18) [  ]
                {
                    qualified_name (3,18) [  ]
                    {
                        simple_name (3,18) [ "int" (3,18) ]
                        {
                        }
                    }
                }
            }
        }
        field_declaration (4,13) [ "pub" (4,9), ":" (4,15), ";" (4,35) ]
        {
            simple_name (4,13) [ "b" (4,13) ]
            {
            }
            vector_type (4,17) [ "[" (4,17), ".." (4,22), "123456789" (4,25), "]" (4,34) ]
            {
                nominal_type (4,18) [  ]
                {
                    qualified_name (4,18) [  ]
                    {
                        simple_name (4,18) [ "foo" (4,18) ]
                        {
                        }
                    }
                }
            }
        }
        field_declaration (5,13) [ "pub" (5,9), ":" (5,15), ";" (5,34) ]
        {
            simple_name (5,13) [ "c" (5,13) ]
            {
            }
            vector_type (5,17) [ "[" (5,17), ".." (5,29), "4" (5,32), "]" (5,33) ]
            {
                tuple_type (5,18) [ "(" (5,18), "," (5,22), ")" (5,27) ]
                {
                    nominal_type (5,19) [  ]
                    {
                        qualified_name (5,19) [  ]
                        {
                            simple_name (5,19) [ "foo" (5,19) ]
                            {
                            }
                        }
                    }
                    nominal_type (5,24) [  ]
                    {
                        qualified_name (5,24) [  ]
                        {
                            simple_name (5,24) [ "bar" (5,24) ]
                            {
                            }
                        }
                    }
                }
            }
        }
    }
}
