Flect.Compiler.Syntax.Token[type: :identifier, value: "asdfdsa", location: Flect.Compiler.Syntax.Location[file: "no_directives.fl", line: 1, column: 1]]
Flect.Compiler.Syntax.Token[type: :string, value: "\"foo\"", location: Flect.Compiler.Syntax.Location[file: "no_directives.fl", line: 2, column: 1]]
Flect.Compiler.Syntax.Token[type: :enum, value: "enum", location: Flect.Compiler.Syntax.Location[file: "no_directives.fl", line: 3, column: 1]]
